version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: finance_tracker
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Backend/backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/finance_tracker
      DATABASE_USERNAME: finance_user
      DATABASE_PASSWORD: finance123
      JWT_SECRET: 73756468656572736563726574666F726A7774746F6B656E73666F72746869736170706C69636174696F6E
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres

  frontend:
    build: ./frontend/pft-UI
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: