spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker
    username: finance_user
    password: finance123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: 73756468656572736563726574666F726A7774746F6B656E73666F72746869736170706C69636174696F6E
  expiration: 86400000